@echo off
echo Стартиране на Ollama сървъра в бекграунд...
start /b ollama serve
echo Изчакваме 3 секунди да зареди...
timeout /t 3 /nobreak > nul
echo Стартиране на V2 теста...
echo Резултатите се записват автоматично във файла: V2_OLLAMA_TEST_RESULTS.txt
python test_ollama_v2.py > V2_OLLAMA_TEST_RESULTS.txt 2>&1
echo Тестът приключи! Отваряне на текстовия файл с резултатите...
start V2_OLLAMA_TEST_RESULTS.txt
